import mongoose from "mongoose";

const attendanceItemSchema = new mongoose.Schema(
  {
    studentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    status: {
      type: String,
      enum: ["present", "absent"],
      default: "absent",
    },
    joinedAt: {
      type: Date,
    },
    leftAt: {
      type: Date,
    },
    note: {
      type: String,
      trim: true,
      default: "",
    },
    markedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
  },
  { _id: false },
);

const liveSessionSchema = new mongoose.Schema(
  {
    courseId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Course",
      required: true,
      index: true,
    },
    teacherId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    title: {
      type: String,
      trim: true,
      required: true,
    },
    description: {
      type: String,
      trim: true,
      default: "",
    },
    platform: {
      type: String,
      enum: ["google_meet", "zoom", "manual", "physical"],
      default: "google_meet",
    },
    timezone: {
      type: String,
      trim: true,
      default: process.env.APP_TIMEZONE || "Asia/Kabul",
    },
    meetingLink: {
      type: String,
      trim: true,
      default: "",
    },
    googleEventId: {
      type: String,
      trim: true,
      default: "",
      index: true,
    },
    googleCalendarId: {
      type: String,
      trim: true,
      default: "",
    },
    startAt: {
      type: Date,
      required: true,
      index: true,
    },
    endAt: {
      type: Date,
      required: true,
      index: true,
    },
    status: {
      type: String,
      enum: [
        "scheduled",
        "ready",
        "live",
        "delayed",
        "completed",
        "cancelled",
        "rescheduled",
        "missed",
      ],
      default: "scheduled",
      index: true,
    },
    sessionNumber: {
      type: Number,
      min: 1,
    },
    actualStartedAt: {
      type: Date,
    },
    actualEndedAt: {
      type: Date,
    },
    notifyStudents: {
      type: Boolean,
      default: true,
    },
    reminderEnabled: {
      type: Boolean,
      default: true,
    },
    autoAttendance: {
      type: Boolean,
      default: false,
    },
    autoGenerated: {
      type: Boolean,
      default: false,
      index: true,
    },
    cancelReason: {
      type: String,
      trim: true,
      default: "",
    },
    attendance: {
      type: [attendanceItemSchema],
      default: [],
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
  },
  { timestamps: true },
);

liveSessionSchema.pre("validate", function () {
  if (Array.isArray(this.attendance)) {
    this.attendance = this.attendance.map((row) => {
      if (row?.status === "late") {
        return { ...row.toObject?.(), ...row, status: "present" };
      }
      if (row?.status === "excused") {
        return { ...row.toObject?.(), ...row, status: "absent" };
      }
      return row;
    });
  }

  if (this.startAt && this.endAt && new Date(this.endAt) <= new Date(this.startAt)) {
    throw new Error("endAt must be after startAt");
  }

  if (this.status !== "cancelled") {
    this.cancelReason = "";
  }
});

liveSessionSchema.index({ teacherId: 1, startAt: 1 });
liveSessionSchema.index({ courseId: 1, startAt: 1 });
liveSessionSchema.index({ courseId: 1, teacherId: 1, startAt: 1 });

const LiveSession = mongoose.model("LiveSession", liveSessionSchema);

export default LiveSession;
